### PR TITLE
Pull Request - Added Template for Reaction Role

### PR DESCRIPTION
**Pull request by ghost**
This Pull Request includes the Template for Reaction Roles and How to link them

### CODE REVIEW

**Review by raluvy95 — CHANGES_REQUESTED** [review]
You dropped a comment here

**Comment by raluvy95** [comment]
also keep `custom/*` in the .gitignore to let others have other file which might not exist in the repo. Put it after `!custom/reactionrole.temp.ts

**Review by ghost — COMMENTED** [review]
I Replaced custom/reactionrole.ts with custom/*, hopefilly it actually worked

**Review by ghost — COMMENTED** [review]
Fixed the comment situation in config.temp.ts

**Review by raluvy95 — APPROVED** [review]

**Comment by raluvy95** [comment]
Gh actions is having skill issue 💀

**Pull request merged**
